language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - trunk


addons:
  sonarqube:
    organization: "1a"
    token:
      secure: "q8OuCp0GtN3byMvwIQzLF08QnV/PK7UQZo6LzD+qQbykhyxM5bBVRELALBAOqpYmn6SJbaEgw2ghilhxgk062qZ7zMuYhu1m5QhZRbzfGZPSMRAfaOOVYW5DpKfOhG0jXeWZjKLQCrs31TskiVuN5reYxeBRkc73elcZ48fciI47FTRpkbeINLOqQiOpzZqkEGkN6l5Ln7azYp1s4pE+2ePTlXyzoGk9Axuu+y/SPUcRxSdgK/tIa2BA5ja5fx2kQUYnWTtFGjKDccxEC60wanPocmVI6TbNUKxwY+l8OUQoqbFTrckOeEG4OOcqKFHF/jMBe7/AIO7mKpSVq1X8SjN6mTUzm0AsjQymrub5u71Oo1sJa0EY+lrleYAnTEVs5CYAh4fifoW1GFzvif0q6dTkZz/JO07XfEfYikB6iUf60kub6L+MbFHpRYeUm6ucZt98h51sdEidQAcqXutIf1vbb7cCcYqBIA4UOW/fHp3nwf/MoI52T4IYQXr9hNIZM3SuX1UfpaNkfizEH6vq2ANm/1d4bfvq7sXZrfD//GniDG4CXhJ7t0i0yoD/bGBhjirVsGWgjI4S4hgnqUbueBCIKz3pTXjtaZHMdQEVQF4oqXcDDsYVj/8WA24RzppW5j6PZfQvkrpJQw9Cgc5CJ7V/hrVgPS8EfvTKXHyrSDU="
      # SONAR_TOKEN as is (/!\ no VAR= /!\)

    # By default only master...
    branches:
      - trunk


env:
  global:
    # GITHUB_TOKEN
    - secure: "jRio1btIZShrN2p/Rc59KZPUt8wdZX0jyToCElSLmgpO9RZCLtE9L95NJXfIRqtfZ/uOzyyhyt7EjpP6Rqy1Nf7MGBlBN7drc8naoLLeYG/au+7HmtsXA0MhGE9FhtAeNCxl/5YmTSZH3B5dWk+PC6yzGrGblZ5oWLGLI+8jyKH/GbzWkYW5OMo8Q2wA7JWhFq1/XKPffu/QjSXhmDkWAga/i/BFsm0sz6wcZVVnKKxfmmKJAfFbLYytr0dKNmpc9d/yp7yN0ShDO/MoZgsk4sM520pPO978q7B8at0wm4xZqfZwQ68GRbA5QckYwzS58jCs42/SAfkK5Cb4+WvizfL6n+0zPIUN40RSV9jDb6m9qEpKs3hjlQT+6hsBQo/fNYUGrR24rhVAh0xmeBIkrq96qWyq3a9gD80SuT5CjSYrG3Wjjbq68OFsBl6I3TpmDdtAWQ6LcYjEgl/eJQ4Bq0o3+qkOtSzJ8EnHxmOhhbNuf7/nOg2k5Ec2lOUFrGo+Mp492HhKwgCboHhGrbmoL+lL/3fKiCeHrZD+j/2TLKo5CQhYm/92nYyhiq513eKKNAaxPTKRIH/V1qpKbWEgJRTCvi22tfgSDvq+fuBMmv4EE0OpnhPhdYENYbWqkAgsnAfpdPCa7KyRkY/1B1UYUE7pR9p/HUKMta8M4n8UQUs="


before_script: true
install: true

script:
  - mvn clean test
  - ./.travis/runSonarQubeAnalysis.sh

after_script: true
