# required for sonar (https://docs.travis-ci.com/user/sonarqube/)
language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - trunk


addons:
  sonarcloud:
    organization: "1a"
    token:
      secure: "q8OuCp0GtN3byMvwIQzLF08QnV/PK7UQZo6LzD+qQbykhyxM5bBVRELALBAOqpYmn6SJbaEgw2ghilhxgk062qZ7zMuYhu1m5QhZRbzfGZPSMRAfaOOVYW5DpKfOhG0jXeWZjKLQCrs31TskiVuN5reYxeBRkc73elcZ48fciI47FTRpkbeINLOqQiOpzZqkEGkN6l5Ln7azYp1s4pE+2ePTlXyzoGk9Axuu+y/SPUcRxSdgK/tIa2BA5ja5fx2kQUYnWTtFGjKDccxEC60wanPocmVI6TbNUKxwY+l8OUQoqbFTrckOeEG4OOcqKFHF/jMBe7/AIO7mKpSVq1X8SjN6mTUzm0AsjQymrub5u71Oo1sJa0EY+lrleYAnTEVs5CYAh4fifoW1GFzvif0q6dTkZz/JO07XfEfYikB6iUf60kub6L+MbFHpRYeUm6ucZt98h51sdEidQAcqXutIf1vbb7cCcYqBIA4UOW/fHp3nwf/MoI52T4IYQXr9hNIZM3SuX1UfpaNkfizEH6vq2ANm/1d4bfvq7sXZrfD//GniDG4CXhJ7t0i0yoD/bGBhjirVsGWgjI4S4hgnqUbueBCIKz3pTXjtaZHMdQEVQF4oqXcDDsYVj/8WA24RzppW5j6PZfQvkrpJQw9Cgc5CJ7V/hrVgPS8EfvTKXHyrSDU="
      # SONAR_TOKEN as is (/!\ no VAR= /!\)

    # Activating comments on PRs
    github_token:
      secure: "TUO/qHymS2LVHBW0tKYR30lgg1XpyHKgume2u/Jf1nEUDAcAGW95Ri4/+iPkYWOSpGZHotbY6XbkKdMTk8W8KVWPmjDenWNZuS54JP1nY+FoaPFYSHrV/cH0cYu3mIDwG5sT/F620ow1dFkzVLoU37OfR7OUk37IiaVKLeejboD8cYz6nTxsgjIFRUdMTtl4owlEwrjqevHsBR87SEASNpwLWsSk9nd3STh0zW4tFNAnGQu+0yQWXq3gsWdddpWUDSdtntKQ1LAt07aaBU88S1cbXoTX12KlWliNUStORkP6gz4fLpPpdzC4w8U0HOuA33M/x2SXs7o20I3m8As2peKX778U33FxNOLiUwKC5CQqVeYW+LE7B7UK3TaA6vUYH3xor02ra9SxkoE5nyQO6NTYEPwXOigY921Wu0d/S6LQD72Iurbe1rCt7cEX+beULCoC5x7afw1WWo+CpvgxiiCpfJ2J3uDAA8OAMGjbZop4R+11Ymr2aRcB6a5ZVB+BcTrted1ktMKP/KOqLg4W86tTHgQU6fkWuX6fhM0SYFhsERlH5zwNJF4aA7zZUa0cmWP2TKQPzNZrl8pFKyKwD+0t45LlCeie1uP3X+6KVaPBzX49YiVynE7fbHn+tccu9K/EYJ0k3gIECjZXHel30ODDJVJNVj9DE06e8bm05oo="

    # By default only master...
    branches:
      - trunk


before_script: true
install: true

script:
  - mvn clean test
  - ./.travis/runSonarQubeAnalysis.sh

after_script: true
